---
abstract: 'base class for App::ZofCMS plugins'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-Base
provides:
  App::ZofCMS::Plugin::Base:
    file: lib/App/ZofCMS/Plugin/Base.pm
    version: 0.0111
requires:
  App::ZofCMS: 0.0106
resources:
  license: http://dev.perl.org/licenses/
version: 0.0111
