---
name: App-ZofCMS-Plugin-Base
version: 0.0105
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: base class for App::ZofCMS plugins
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS: 0.0106
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::Base:
    file: lib/App/ZofCMS/Plugin/Base.pm
    version: 0.0105
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
